Start Transaction ACT
pagopa/pn-radd-alt pull request #15
Opened 2024-02-06 10:21 UTC by marcellosattanttdata

2024-02-06 16:51 UTC, fabriziolana requested changes

2024-02-06 16:51 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/radd/services/radd/fsu/v1/ActService.java
> +                        .mapNotNull(NotificationAttachmentDownloadMetadataResponseDto::getUrl))
Qui se non ricordo male, c'era da loggare a fatal il fatto che un documento di una notifica non ricevesse il presignedurl ma il retryAfter (era il caso "che non doveva succedere").
Vedete voi se loggarlo qui o in un altro punto comunque.

2024-02-06 17:01 UTC, empassaro commented on src/main/java/it/pagopa/pn/radd/services/radd/fsu/v1/ActService.java
> +                        .mapNotNull(NotificationAttachmentDownloadMetadataResponseDto::getUrl))
Si, in effetti è da riportare e ce lo siamo appuntati. Però ci siamo resi conto che il microservizio non rispetta le linee guida condivise su confluence per la gestione dei log tramite AOP. Quindi pensavamo di reintervenire in merito mentre aggiungiamo anche gli audit log.

2024-02-07 07:58 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/radd/services/radd/fsu/v1/ActService.java
> +                        .mapNotNull(NotificationAttachmentDownloadMetadataResponseDto::getUrl))
ok allora

2024-02-07 07:58 UTC, fabriziolana approved these changes

2024-02-07 08:05 UTC, merged